### ISSUE TITLE
missing dependency on generated package.json: eslint-plugin-vuetify

### ISSUE THREAD

**Issue by userquin** [vuetifyjs/vue-cli-preset-vuetify#4]
yarn install fails once the project is generated:

```shell
F:\work\projects\quini\vuejs\vuetify-preset-test>vue info

Environment Info:

  System:
    OS: Windows 10
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @storybook/vue: ^5.2 => 5.2.8
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.1.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.1
    @vue/cli-plugin-babel: ^4.1.0 => 4.1.1
    @vue/cli-plugin-e2e-cypress: ^4.1.0 => 4.1.1
    @vue/cli-plugin-eslint: ^4.1.0 => 4.1.1
    @vue/cli-plugin-router: ^4.1.0 => 4.1.1
    @vue/cli-plugin-unit-jest: ^4.1.0 => 4.1.1
    @vue/cli-plugin-vuex: ^4.1.0 => 4.1.1
    @vue/cli-service: ^4.1.0 => 4.1.1
    @vue/cli-shared-utils:  4.1.1
    @vue/component-compiler-utils:  3.1.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  3.7.0
    babel-preset-vue: ^2.0.2 => 2.0.2
    eslint-config-vuetify: * => 0.4.1
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (6.0.1)
    eslint-plugin-vuetify:  undefined (1.0.0-beta.6)
    jest-serializer-vue:  2.0.2
    vue: ^2.6.10 => 2.6.11
    vue-analytics: * => 5.20.1
    vue-class-component:  7.1.0
    vue-cli-plugin-prerender-spa: latest => 1.1.6
    vue-cli-plugin-vuetify: latest => 2.0.2
    vue-cli-plugin-vuetify-cli: latest => 0.0.6
    vue-cli-plugin-vuetify-essentials: latest => 0.8.3
    vue-cli-plugin-vuetify-storybook: latest => 0.1.1
    vue-eslint-parser:  5.0.0 (6.0.5)
    vue-hot-reload-api:  2.3.4
    vue-jest:  3.0.5
    vue-loader:  15.8.3
    vue-meta: * => 2.3.1
    vue-router: ^3.1.3 => 3.1.3
    vue-storybook: ^1.1.0 => 1.2.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuetify: ^2.1.0 => 2.1.15
    vuetify-loader: ^1.3.0 => 1.4.3
    vuex: ^3.1.2 => 3.1.2
    vuex-pathify: * => 1.4.1
    vuex-router-sync: * => 5.0.0
  npmGlobalPackages:
    @vue/cli: Not Found

```
Command error:

```shell
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 95.82s.
 ERROR  Error: Failed to load plugin vuetify: Cannot find module 'eslint-plugin-vuetify'
Referenced from: F:\work\projects\quini\vuejs\vuetify-preset-test\.eslintrc.js
Error: Failed to load plugin vuetify: Cannot find module 'eslint-plugin-vuetify'
Referenced from: F:\work\projects\quini\vuejs\vuetify-preset-test\.eslintrc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Plugins.load (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\config\plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\config\plugins.js:165:21)
    at loadFromDisk (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\config\config-file.js:529:35)
    at load (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\config\config-file.js:587:20)
    at configExtends.reduceRight (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\config\config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\config\config-file.js:431:26)
```

**Comment by userquin** [comment]
Once added dependency `yarn add -D eslint-plugin-vuetify`, there are some errors on `yarn serve`:

```shell
F:\work\projects\quini\vuejs\vuetify-preset-test>yarn serve
yarn run v1.16.0
$ vue-cli-service serve
 INFO  Starting development server...
40% building 26/29 modules 3 active ...index.js??ref--13-0!F:\work\projects\quini\vuejs\vuetify-preset-test\src\App.vue(node:19192) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
40% building 226/299 modules 73 active ...vuejs\vuetify-preset-test\node_modules\vuetify\lib\directives\scroll\index.js(node:19192) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
44% building 289/304 modules 15 active ...ni\vuejs\vuetify-preset-test\node_modules\core-js\internals\array-for-each.js(node:19192) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
98% after emitting CopyPlugin

 ERROR  Failed to compile with 3 errors                                                                       8:23:51 PM

 error  in ./src/main.js

Module Error (from ./node_modules/eslint-loader/index.js):
error: Extra semicolon (semi) at src\main.js:5:40:
  3 | import router from './router'
  4 | import store from './store'
> 5 | import vuetify from './plugins/vuetify';
    |                                        ^
  6 | import './plugins'
  7 |
  8 | Vue.config.productionTip = false


error: Missing trailing comma (comma-dangle) at src\main.js:14:22:
  12 |   store,
  13 |   vuetify,
> 14 |   render: h => h(App)
     |                      ^
  15 | }).$mount('#app')
  16 |


2 errors found.
2 errors potentially fixable with the `--fix` option.

 @ multi (webpack)-dev-server/client?http://192.168.1.37:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/plugins/vuetify.js

Module Error (from ./node_modules/eslint-loader/index.js):
error: Missing trailing comma (comma-dangle) at src\plugins\vuetify.js:30:17:
  28 |       mdiMonitorCellphone,
  29 |       mdiMonitorDashboard,
> 30 |       mdiVuetify
     |                 ^
  31 |     },
  32 |   },
  33 |   theme: {


1 error found.
1 error potentially fixable with the `--fix` option.

 @ ./src/main.js 9:0-40 15:11-18
 @ multi (webpack)-dev-server/client?http://192.168.1.37:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/router/index.js

Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
Occurred while linting F:\work\projects\quini\vuejs\vuetify-preset-test\src\router\index.js:14
    at SourceCode.getTokenBefore (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\token-store\index.js:303:18)
    at checkSpacingBefore (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\rules\template-curly-spacing.js:60:42)
    at TemplateElement (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\rules\template-curly-spacing.js:119:17)
    at listeners.(anonymous function).forEach.listener (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\linter.js:752:32)
    at Array.forEach (<anonymous>)
    at runRules (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\linter.js:747:15)
    at Linter._verifyWithoutProcessors (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\linter.js:899:31)
    at preprocess.map.textBlock (F:\work\projects\quini\vuejs\vuetify-preset-test\node_modules\eslint\lib\linter.js:955:35)
    at Array.map (<anonymous>)

 @ ./src/main.js 7:0-30 13:10-16
 @ multi (webpack)-dev-server/client?http://192.168.1.37:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by userquin** [comment]
For `eslint-loader` error, just configure these rules to `.eslintrec.js` (https://github.com/babel/babel-eslint/issues/681#issuecomment-420663038):

```js
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'template-curly-spacing' : 'off',
    'indent' : 'off'
  },
```

**Comment by deka** [comment]
Hi,
Same error, do you have a workaround ?
